### ISSUE TITLE
_mysql import error

### ISSUE THREAD

**Issue by klimovskis** [nonbeing/mysqlclient-python3-aws-lambda#11]
Thanks for the repo! 
When importing MySQLdb there is a problem occurring

`Response
{
  "errorMessage": "name '_mysql' is not defined",
  "errorType": "NameError",
  "requestId": "",
  "stackTrace": [
    "  File \"/var/lang/lib/python3.9/importlib/__init__.py\", line 127, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n",
    "  File \"<frozen importlib._bootstrap>\", line 1030, in _gcd_import\n",
    "  File \"<frozen importlib._bootstrap>\", line 1007, in _find_and_load\n",
    "  File \"<frozen importlib._bootstrap>\", line 986, in _find_and_load_unlocked\n",
    "  File \"<frozen importlib._bootstrap>\", line 680, in _load_unlocked\n",
    "  File \"<frozen importlib._bootstrap_external>\", line 850, in exec_module\n",
    "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\n",
    "  File \"/var/task/lambda_function.py\", line 3, in <module>\n    import MySQLdb\n",
    "  File \"/opt/python/MySQLdb/__init__.py\", line 24, in <module>\n    version_info, _mysql.version_info, _mysql.__file__\n"
  ]
}

Function Logs
[ERROR] NameError: name '_mysql' is not defined
Traceback (most recent call last):
  File "/var/lang/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/task/lambda_function.py", line 3, in <module>
    import MySQLdb
  File "/opt/python/MySQLdb/__init__.py", line 24, in <module>
    version_info, _mysql.version_info, _mysql.__file__[ERROR] NameError: name '_mysql' is not defined
Traceback (most recent call last):
  File "/var/lang/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/task/lambda_function.py", line 3, in <module>
    import MySQLdb
  File "/opt/python/MySQLdb/__init__.py", line 24, in <module>
    version_info, _mysql.version_info, _mysql.__file__START RequestId: a0059910-5ae6-46f8-b920-bc1545b1bef4 Version: $LATEST
Unknown application error occurred`

**Comment by nonbeing** [comment]
I'm guessing the layer was not added correctly to the Lambda function. Or the layer  was not correctly created with the right .so file.

There could be various reasons.

**Comment by klimovskis** [comment]
Hello, thanks for reply. 

I added layer as a zip file following your instruction. Then I added layer. Arm, python 3.9.

**Comment by klimovskis** [comment]
I have tried creating a new function, but still the problem.

**Comment by nonbeing** [comment]
Ah - it might be ARM then. Because I have never tested this on ARM.

**Comment by klimovskis** [comment]
Just tested. Works on x84 but not on arm. Thanks.

**Comment by nonbeing** [comment]
Thank you for trying it out and updating back here 👍
